#̷\  ===================================================================
#̷\  PowerShell Module -- PowerShell.Module.Assert
#̷\  
#̷\  Manifest File Generated on Fri, 29 Sep 2023 15:26:46 GMT
#̷\  Current Git Revision d14c3e272986bc21ce0f1074b29d07269a6a34fb
#̷\  ===================================================================


@{


    RootModule        =  'PowerShell.Module.Assert.psm1'

    ModuleVersion     = '1.0.155'

    GUID              = '2c1ca10f-917c-4ced-908c-88a4a000644e'

    CompanyName       = 'Unknown'

    Author            = 'Guillaume Plante'

    Copyright         = '(c) 2020 Guillaume Plante. All rights reserved.'

    Description       = 'MODULE PowerShell.Module.ASsert on 2:31 AM'

    PowerShellVersion = '5.0'

    RequiredAssemblies = @()

    # Private data to pass to the module specified in RootModule. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('PowerShell.Module.Assert')
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/arsscriptum/PowerShell.Module.Assert/blob/main/COPYING'
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/arsscriptum/PowerShell.Module.Assert'
        } # End of PSData hashtable
    } # End of PrivateData hashtable


    #̷\  ===================================================
    #̷\     ＭＯＤＵＬＥ ＥＸＰＯＲＴＥＤ ＦＵＮＣＴＩＯＮＳ
    #̷\  ===================================================

	# !NOTE! --- The following functions declaration was automatically generated by the build script. ---
	FunctionsToExport = @(

		# --- Exported Functions from AddAssertionException.ps1 ---
		"Get-AssertModuleInformation",
		"Get-AssertModuleExportsPath",
		"Register-AssertionException",

		# --- Exported Functions from AssertAll.ps1 ---
		"Assert-All",

		# --- Exported Functions from AssertAny.ps1 ---
		"Assert-Any",

		# --- Exported Functions from AssertContain.ps1 ---
		"Assert-Contain",

		# --- Exported Functions from AssertEqual.ps1 ---
		"Assert-Equal",

		# --- Exported Functions from AssertEquivalent.ps1 ---
		"Compare-Equivalent",
		"Compare-ObjectEquivalent",
		"Compare-DictionaryEquivalent",
		"Compare-HashtableEquivalent",
		"Compare-ValueEquivalent",
		"Get-ValueNotEquivalentMessage",
		"Get-CollectionSizeNotTheSameMessage",
		"Assert-Equivalent",
		"Is-CollectionSize",
		"Test-Same",
		"Compare-CollectionEquivalent",

		# --- Exported Functions from AssertFalse.ps1 ---
		"Assert-False",

		# --- Exported Functions from AssertGreaterThan.ps1 ---
		"Assert-GreaterThan",

		# --- Exported Functions from AssertGreaterThanOrEqual.ps1 ---
		"Assert-GreaterThanOrEqual",

		# --- Exported Functions from AssertLessThan.ps1 ---
		"Assert-LessThan",

		# --- Exported Functions from AssertLessThanOrEqual.ps1 ---
		"Assert-LessThanOrEqual",

		# --- Exported Functions from AssertLike.ps1 ---
		"Test-Like",
		"Get-LikeDefaultFailureMessage",
		"Assert-Like",

		# --- Exported Functions from AssertNotContain.ps1 ---
		"Assert-NotContain",

		# --- Exported Functions from AssertNotEqual.ps1 ---
		"Assert-NotEqual",

		# --- Exported Functions from AssertNotLike.ps1 ---
		"Assert-NotLike",
		"Get-NotLikeDefaultFailureMessage",
		"Test-NotLike",

		# --- Exported Functions from AssertNotNull.ps1 ---
		"Assert-NotNull",

		# --- Exported Functions from AssertNotSame.ps1 ---
		"Assert-NotSame",

		# --- Exported Functions from AssertNotType.ps1 ---
		"Assert-NotType",

		# --- Exported Functions from AssertNull.ps1 ---
		"Assert-Null",

		# --- Exported Functions from AssertSame.ps1 ---
		"Assert-Same",

		# --- Exported Functions from AssertStringEqual.ps1 ---
		"Test-StringEqual",
		"Get-StringEqualDefaultFailureMessage",
		"Assert-StringEqual",

		# --- Exported Functions from AssertStringNotEqual.ps1 ---
		"Assert-StringNotEqual",
		"Get-StringNotEqualDefaultFailureMessage",

		# --- Exported Functions from AssertThrow.ps1 ---
		"Assert-Throw",
		"Get-Error",
		"Join-And",
		"Add-SpaceToNonEmptyString",

		# --- Exported Functions from AssertTrue.ps1 ---
		"Assert-True",

		# --- Exported Functions from AssertType.ps1 ---
		"Assert-Type",

		# --- Exported Functions from CollectInput.ps1 ---
		"Collect-Input",

		# --- Exported Functions from EnsureExpectedIsNotCollection.ps1 ---
		"Ensure-ExpectedIsNotCollection",

		# --- Exported Functions from Format.ps1 ---
		"Format-Type",
		"Get-DisplayProperty",
		"Format-Nicely",
		"Format-Dictionary",
		"Format-Hashtable",
		"Get-ShortType",
		"Format-ScriptBlock",
		"Format-Boolean",
		"Format-Null",
		"Format-Object",
		"Format-Collection",
		"Format-Number",

		# --- Exported Functions from GetAssertionMessage.ps1 ---
		"Get-AssertionMessage",

		# --- Exported Functions from GetCustomFailureMessage.ps1 ---
		"Get-CustomFailureMessage",

		# --- Exported Functions from NewPSObject.ps1 ---
		"New-PSObject",

		# --- Exported Functions from TypeClass.ps1 ---
		"Is-Object",
		"Is-Dictionary",
		"Is-Hashtable",
		"Is-ScriptBlock",
		"Is-Collection",
		"Is-Value",
		"Is-DecimalNumber",

		# --- Exported Functions from VerifyAssertionFailed.ps1 ---
		"Verify-AssertionFailed",

		# --- Exported Functions from VerifyEqual.ps1 ---
		"Verify-Equal",

		# --- Exported Functions from VerifyFalse.ps1 ---
		"Verify-False",

		# --- Exported Functions from VerifyNotNull.ps1 ---
		"Verify-NotNull",

		# --- Exported Functions from VerifyNotSame.ps1 ---
		"Verify-NotSame",

		# --- Exported Functions from VerifyNull.ps1 ---
		"Verify-Null",

		# --- Exported Functions from VerifySame.ps1 ---
		"Verify-Same",

		# --- Exported Functions from VerifyThrow.ps1 ---
		"Verify-Throw",

		# --- Exported Functions from VerifyTrue.ps1 ---
		"Verify-True",

		# --- Exported Functions from VerifyType.ps1 ---
		"Verify-Type")
	

    #̷\  ===================================================
    #̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＥＸＰＯＲＴＥＤ ＡＬＩＡＳＥＳ
    #̷\  ===================================================

	# !NOTE! --- The following alias declaration was automatically generated by the build script. ---
	# List of all aliases packaged with this module

	AliasesToExport = @()

    #̷\  ===================================================
    #̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＦＩＬＥＳ 
    #̷\ （ＩＦ ＣＯＭＰＲＥＳＳＥＤ， ＷＩＬＬ ＢＥ ＥＭＰＴＹ）
    #̷\  ===================================================

	FileList = @()

}




